pipeline {
    agent any
    stages {
        stage('clean up') {
        when{
        anyOf{
            branch 'main'
            }
        }
            steps {
                cleanWs()
                echo 'Building..'
                script{
                 last_started  = env.STAGE_NAME
                }
            }
        }
        stage('Checkout all') {
            steps {
                echo 'Testing..'
                userRemoteConfigs: ([credentialsId: 'Zhyldyza', url: 'https://github.com/Zhyldyza/JsonPlaceholder.git'])
            }
        }
        stage('Deploy') {
        when{
         anyOf{
          branch 'master'
         }
        }
            steps {
                echo 'Deploying....'
            script {
                last_started = env.STAGE_NAME
                sh 'echo ${ENVIRONMENT}'
                dir('chart'){
                 git branch: "main"
                    credentialsId: 'Zhyldyza'
                    url: 'https://github.com/Zhyldyza/JsonPlaceholder.git'
                }
             }
            }
        }
    }
}