pipeline {
    agent any
    stages {
     stage('Checkout') {
                steps {
                    echo 'Testing..'
                    git 'https://github.com/Zhyldyza/JsonPlaceholder.git'
                    checkout scm
                }
            }

        stage('Build') {
        when{
        anyOf{
            branch 'main'
            }
        }
            steps {
                cleanWs()
                echo 'Building..'
                script{
                 last_started  = env.STAGE_NAME
                 sh 'mvn clean package'
                }
            }
        }

        stage('Test'){
        }

        stage('Deploy') {
        when{
         anyOf{
          branch 'master'
         }
        }
            steps {
                echo 'Deploying....'
            script {
                last_started = env.STAGE_NAME
                sh 'echo ${ENVIRONMENT}'
                dir('chart'){
                 git branch: "main"
                    credentialsId: 'Zhyldyza'
                    url: 'https://github.com/Zhyldyza/JsonPlaceholder.git'
                }
              }
            }
        }
    }
}